// DTA Cookies Sync - Background Service Worker
// Sản phẩm của DTA STUDIO - Phát triển bởi Đức Trường AI

const DEFAULT_PORT = 8732;

// Định kỳ đồng bộ mỗi 15 phút
chrome.alarms.create("sync-cookies-alarm", { periodInMinutes: 15 });

chrome.alarms.onAlarm.addListener((alarm) => {
  if (alarm.name === "sync-cookies-alarm") {
    syncAllCookies();
  }
});

// Đồng bộ khi có sự thay đổi cookie của YouTube hoặc Bilibili
chrome.cookies.onChanged.addListener((changeInfo) => {
  const domain = changeInfo.cookie.domain;
  if (domain.includes("youtube.com") || domain.includes("bilibili.com")) {
    // Tránh spam request liên tục bằng debounce
    debounceSync();
  }
});

let syncTimeout = null;
function debounceSync() {
  if (syncTimeout) clearTimeout(syncTimeout);
  syncTimeout = setTimeout(() => {
    syncAllCookies();
  }, 5000); // Đợi 5 giây sau lần thay đổi cuối cùng
}

async function getSyncPort() {
  return new Promise((resolve) => {
    chrome.storage.local.get(["syncPort"], (result) => {
      resolve(result.syncPort || DEFAULT_PORT);
    });
  });
}

function formatCookieNetscape(c) {
  // Định dạng Netscape Cookie Format:
  // domain 	 is_domain_starting_with_dot 	 path 	 is_secure 	 expiration 	 name 	 value
  const domain = c.domain;
  const isDomainDot = domain.startsWith(".") ? "TRUE" : "FALSE";
  const path = c.path || "/";
  const isSecure = c.secure ? "TRUE" : "FALSE";
  const expiration = c.expirationDate ? Math.round(c.expirationDate) : 0;
  const name = c.name;
  const value = c.value;
  
  return `${domain}	${isDomainDot}	${path}	${isSecure}	${expiration}	${name}	${value}`;
}

async function syncAllCookies() {
  const port = await getSyncPort();
  const domains = ["youtube.com", "bilibili.com"];
  let netscapeLines = [
    "# Netscape HTTP Cookie File",
    "# This file was generated automatically by DTA Cookies Sync Extension.",
    "# http://curl.haxx.se/rfc/cookie_spec.html",
    "# Do not edit this file manually!",
    ""
  ];

  try {
    for (const dom of domains) {
      const cookies = await chrome.cookies.getAll({ domain: dom });
      cookies.forEach(c => {
        netscapeLines.push(formatCookieNetscape(c));
      });
    }

    const cookieContent = netscapeLines.join("\n");
    const response = await fetch(`http://127.0.0.1:${port}/update-cookies`, {
      method: "POST",
      headers: {
        "Content-Type": "text/plain"
      },
      body: cookieContent
    });

    if (response.ok) {
      console.log("✅ Đồng bộ cookies thành công qua port " + port);
      chrome.runtime.sendMessage({ status: "success", time: new Date().toLocaleTimeString() }).catch(() => {});
    } else {
      console.error("❌ Đồng bộ cookies thất bại");
      chrome.runtime.sendMessage({ status: "failed", error: "Server từ chối nhận cookies" }).catch(() => {});
    }
  } catch (err) {
    console.error("❌ Lỗi kết nối đến DTA AutoDown:", err);
    chrome.runtime.sendMessage({ status: "failed", error: "Không kết nối được ứng dụng. Đảm bảo app đang chạy và đã bật DTA Cookies Sync!" }).catch(() => {});
  }
}

// Lắng nghe yêu cầu đồng bộ ngay từ Popup UI
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.action === "sync-now") {
    syncAllCookies().then(() => {
      sendResponse({ status: "processing" });
    });
    return true;
  }
});
